# ==========================================
# Configuración de Aanon Identity
# ==========================================
# Genera tu clave única interactuando con el bot de Discord.

plugin_key: 'PON_TU_CLAVE_AQUI'
